### ISSUE TITLE
Social media links - not working

### ISSUE THREAD

**Issue by lauuuuuura** [lauuuuuura/lauuuuuura.github.io#1]
Social media links (in footer) are not working on the Home page.
Jekyll generates the footer in the _default_ layout. This layout is used in both index.html and blog.html pages. The bug is reproduced only in the first page.

**Comment by razvancrainea** [comment]
It does work on Android browsers though.

**Comment by razvancrainea** [comment]
Actually only the linkedin link works; facebook doesn't.

**Comment by razvancrainea** [comment]
Still not working on Android.

**Comment by lauuuuuura** [comment]
Will look into this
